disabled_rules: # rule identifiers to exclude from running

opt_in_rules: # some rules are only opt-in
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_string
 # - explicit_enum_raw_value
 # - file_name
#  - file_types_order
  - first_where
#  - force_unwrapping
  - identical_operands
#  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
 # - multiline_arguments_brackets
 # - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - nsobject_prefer_isequal
#  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - reduce_into
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_first_last
  - sorted_imports
  - static_operator
  - switch_case_on_newline
  - toggle_bool
#  - trailing_closure
#  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - BSC
  - BSCTests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

empty_count: error
empty_string: error
let_var_whitespace: error
function_parameter_count:
  - 10
  - 10

closure_body_length:
  warning: 30

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: error # implicitly
force_try:
  severity: error # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 400
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: 1 # only min_length
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
